// guest periods enum
export enum GuestPeriodsEnum {
	ADHOC = 'ADHOC',
	FIRST_LOGIN = 'FIRST_LOGIN',
	MIDDLE_STAY = 'MIDDLE_STAY',
	DAY_AFTER_CHECKIN = 'DAY_AFTER_CHECKIN',
	DAY_BEFORE_CHECKOUT = 'DAY_BEFORE_CHECKOUT'
}
