// user role
export enum UserRoleEnum {
	ADMIN = 'ADMIN',
	GROUP_MANAGER = 'GROUP_MANAGER',
	HOTEL_MANAGER = 'HOTEL_MANAGER',
	HOTEL_SUB_MANAGER = 'HOTEL_SUB_MANAGER',
	HOUSEKEEPING = 'HOUSEKEEPING'
}
