// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_cognito_identity_pool_id": "eu-central-1:16551f3d-72da-4362-8f7d-babb99e2ea6f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_okViFvvPn",
    "aws_user_pools_web_client_id": "1gp9m9i1475urd1kt0v6tubobf"
};

export default awsmobile;
